[project]
name = "cv-perfector"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.4",
    "langchain>=0.3.7",
    "markdown-to-json>=2.1.2",
    "pydantic>=2.9.2",
    "pymupdf4llm>=0.0.17",
]
